# Generated by Django 3.2.10 on 2021-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notices',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
