# Generated by Django 3.2.10 on 2021-12-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211220_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dashboarduser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
