# Generated by Django 3.2.10 on 2021-12-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicepayments',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='service_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.servicetype'),
            preserve_default=False,
        ),
    ]
