# Generated by Django 3.2.10 on 2022-01-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dashboarduser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='current_earn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrank',
            name='sale_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
