# Generated by Django 3.2.10 on 2022-03-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_services_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
