# Generated by Django 3.2.12 on 2022-03-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_services_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='extra_comm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='services',
            name='limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
