# Generated by Django 3.2.12 on 2022-04-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220329_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='commission',
        ),
        migrations.RemoveField(
            model_name='services',
            name='extra_comm',
        ),
        migrations.RemoveField(
            model_name='services',
            name='limit',
        ),
        migrations.AddField(
            model_name='service',
            name='cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='comm_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='commission',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
