# Generated by Django 3.2.12 on 2022-04-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_order_orderitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='variance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.variableproductprice'),
        ),
    ]
