# Generated by Django 3.2.12 on 2022-05-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20220521_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='contributor',
        ),
        migrations.CreateModel(
            name='PortfolioContributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dashboarduser')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.portfolio')),
            ],
        ),
    ]
