# Generated by Django 3.2.12 on 2022-05-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_serviceproduct_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trx_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
