# Generated by Django 3.2.12 on 2022-05-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_payment_trx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableproductprice',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
