# Generated by Django 3.2.12 on 2022-06-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_variableproductprice_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_payment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
