# Generated by Django 3.2.12 on 2022-06-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_order_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=128, null=True)),
                ('lname', models.CharField(blank=True, max_length=128, null=True)),
                ('telid', models.CharField(blank=True, max_length=128, null=True)),
                ('subject', models.CharField(blank=True, max_length=256, null=True)),
                ('social', models.CharField(blank=True, max_length=128, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
