# Generated by Django 3.2.12 on 2022-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20220606_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variableproductprice',
            name='base_price',
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='base_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceproduct',
            name='base_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
