# Generated by Django 3.2.12 on 2022-06-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_orderitems_new_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='new_order',
        ),
        migrations.AddField(
            model_name='order',
            name='new_order',
            field=models.BooleanField(default=True),
        ),
    ]
