# Generated by Django 3.2.12 on 2022-06-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_productterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='cryptoProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.ImageField(blank=True, null=True, upload_to='crypto_proof', verbose_name='crypto_proof')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.serviceproduct')),
            ],
        ),
        migrations.CreateModel(
            name='cryptoNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(blank=True, max_length=128, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.serviceproduct')),
            ],
        ),
    ]
