# Generated by Django 3.2.12 on 2022-06-11 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_cryptonetwork_cryptoproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoproof',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serviceproduct'),
        ),
    ]
