# Generated by Django 3.2.12 on 2022-06-11 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_cryptoproof_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptonetwork',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cryptoproof',
            name='product',
        ),
        migrations.AddField(
            model_name='cryptonetwork',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cryptoproof',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
            preserve_default=False,
        ),
    ]
