# Generated by Django 3.2.12 on 2022-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20220611_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptonetwork',
            name='payment_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
