# Generated by Django 3.2.12 on 2022-06-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_cryptonetwork_payment_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
