# Generated by Django 3.2.12 on 2022-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_orderitems_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='reference',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
