# Generated by Django 3.2.12 on 2022-06-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='variableproductprice',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
