# Generated by Django 3.2.12 on 2022-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='news_thumbs', verbose_name='news_thumbs'),
        ),
    ]
