# Generated by Django 3.2.12 on 2022-07-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_order_cancelled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
